"""
app/services/auth_service.py

Authentication business logic.

This layer sits between the route handlers (HTTP) and the database (storage).
It contains NO FastAPI imports except HTTPException — which is a domain
exception, not an HTTP transport concern. No Request, no Response, no Depends.

Why a service layer?
  - Routes are thin: they validate input, call services, return output.
  - Services are testable without HTTP: call them directly in tests.
  - If you switch from FastAPI to gRPC, only the route layer changes.

Each function follows this pattern:
  1. Business rule validation (uniqueness checks, state checks)
  2. Data transformation (hashing, token generation)
  3. Persistence (DB write + Redis write)
  4. Return domain objects (not HTTP responses)
"""

import uuid
from decimal import Decimal

from fastapi import HTTPException, status
from redis.asyncio import Redis
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.security import (
    create_access_token,
    create_refresh_token,
    delete_refresh_token,
    get_refresh_token,
    hash_password,
    store_refresh_token,
    verify_password_timing_safe,
)
from app.models.user import User
from app.models.wallet import Wallet, WalletCurrency
from app.schemas.auth import RegisterRequest, LoginRequest


# =============================================================================
# register_user
# =============================================================================

async def register_user(
    db: AsyncSession,
    redis: Redis,
    request: RegisterRequest,
) -> tuple[User, str, str]:
    """
    Register a new user and create their default USD wallet.

    Atomicity is critical here:
    - User creation + Wallet creation happen in ONE database transaction.
    - If wallet creation fails, the user row is rolled back automatically.
    - A user without a wallet is an invalid state in a wallet application.

    The approach:
      db.add(user) → db.flush() → db.add(wallet) → db.commit()

    Why flush() before commit()?
    flush() writes the user row to the DB within the current transaction
    (so we can access user.id for the wallet FK) but does NOT commit.
    If wallet creation raises an exception, the entire transaction rolls back —
    including the user row that was flushed.

    Security:
    - Email uniqueness is checked at the application layer for a friendly
      error message. The DB UNIQUE constraint is the final enforcement.
    - Password is hashed BEFORE the DB write — never store plaintext.
    - Registration returns tokens immediately so the client doesn't need
      to call /login separately after registration.

    Args:
        db: Async SQLAlchemy session (injected by FastAPI dependency).
        redis: Async Redis client (injected by FastAPI dependency).
        request: Validated RegisterRequest schema.

    Returns:
        Tuple of (user, access_token, refresh_token).

    Raises:
        HTTPException 409: Email already registered.
    """

    # -------------------------------------------------------------------------
    # Step 1: Check email uniqueness
    # We check at the application layer to return 409 (Conflict) with a clear
    # message. Without this, PostgreSQL would raise an IntegrityError and
    # the user would get a 500 Internal Server Error.
    # -------------------------------------------------------------------------
    existing_user = await db.scalar(
        select(User).where(User.email == str(request.email))
    )
    if existing_user is not None:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="An account with this email address already exists",
        )

    # -------------------------------------------------------------------------
    # Step 2: Hash the password
    # This runs bcrypt (12 rounds, ~250ms). Done before any DB operation
    # so we don't hold a DB transaction open during the slow hashing.
    # -------------------------------------------------------------------------
    hashed_pw = hash_password(request.password)

    # -------------------------------------------------------------------------
    # Step 3: Create User and Wallet atomically
    # Both operations share the same SQLAlchemy session = same transaction.
    # -------------------------------------------------------------------------
    user = User(
        email=str(request.email),
        full_name=request.full_name,
        phone_number=request.phone_number,
        hashed_password=hashed_pw,
        # role, is_active, is_verified all use their model defaults
    )
    db.add(user)

    # flush() assigns user.id (generated by PostgreSQL) without committing.
    # We need user.id to set wallet.user_id in the next step.
    await db.flush()

    wallet = Wallet(
        user_id=user.id,
        currency=WalletCurrency.USD,
        balance=Decimal("0.00000000"),
        wallet_tag="primary",
        is_active=True,
    )
    db.add(wallet)

    # commit() finalizes BOTH the user and wallet row in one atomic write.
    # If this raises (e.g., DB unavailable), no partial data is persisted.
    await db.commit()

    # refresh() re-reads the user from DB to populate server-side defaults
    # (created_at, updated_at via server_default=func.now()).
    await db.refresh(user)

    # -------------------------------------------------------------------------
    # Step 4: Generate JWT token pair
    # -------------------------------------------------------------------------
    access_token = create_access_token(user.id)
    refresh_token = create_refresh_token(user.id)

    # -------------------------------------------------------------------------
    # Step 5: Store refresh token in Redis
    # This happens AFTER the DB commit — if Redis is down, user data is safe.
    # The user would simply need to login again (no refresh token stored).
    # -------------------------------------------------------------------------
    await store_refresh_token(redis, user.id, refresh_token)

    return user, access_token, refresh_token


# =============================================================================
# login_user
# =============================================================================

async def login_user(
    db: AsyncSession,
    redis: Redis,
    request: LoginRequest,
) -> tuple[User, str, str]:
    """
    Authenticate a user by email and password.

    Security design:
    - We always return the same error for "email not found" and "wrong password".
      Distinguishing them would let attackers enumerate valid email addresses.
    - We use timing-safe verification even when the user isn't found
      (see verify_password_timing_safe in security.py).
    - Logging in from a new device REPLACES the existing refresh token in Redis.
      This means the previous device's session is silently invalidated.
      Multi-device sessions are a Phase 3 feature.

    Args:
        db: Async SQLAlchemy session.
        redis: Async Redis client.
        request: Validated LoginRequest schema.

    Returns:
        Tuple of (user, access_token, refresh_token).

    Raises:
        HTTPException 401: Invalid credentials (email or password incorrect).
        HTTPException 403: Account is disabled.
    """

    # -------------------------------------------------------------------------
    # Step 1: Find user by email
    # selectinload not needed here — we don't need wallets for login.
    # -------------------------------------------------------------------------
    user = await db.scalar(
        select(User).where(User.email == str(request.email))
    )

    # -------------------------------------------------------------------------
    # Step 2: Verify password (timing-safe)
    # verify_password_timing_safe() runs bcrypt even when user is None,
    # so both "user not found" and "wrong password" take ~250ms.
    # This prevents email enumeration via response timing.
    # -------------------------------------------------------------------------
    password_matches = verify_password_timing_safe(
        request.password,
        user.hashed_password if user is not None else None,
    )

    if not password_matches:
        # Generic message: don't reveal whether the email exists
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid email or password",
            headers={"WWW-Authenticate": "Bearer"},
        )

    # -------------------------------------------------------------------------
    # Step 3: Check account status
    # Only after credential verification — don't reveal account existence
    # before the user proves they know the password.
    # -------------------------------------------------------------------------
    if not user.is_active:  # type: ignore[union-attr]
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="This account has been disabled. Contact support.",
        )

    # -------------------------------------------------------------------------
    # Step 4: Generate new token pair and store refresh token
    # store_refresh_token() uses SET which overwrites any existing token.
    # If the user was logged in on another device, that session is now invalid.
    # -------------------------------------------------------------------------
    access_token = create_access_token(user.id)  # type: ignore[union-attr]
    refresh_token = create_refresh_token(user.id)  # type: ignore[union-attr]
    await store_refresh_token(redis, user.id, refresh_token)  # type: ignore[union-attr]

    return user, access_token, refresh_token  # type: ignore[return-value]


# =============================================================================
# refresh_tokens
# =============================================================================

async def refresh_tokens(
    db: AsyncSession,
    redis: Redis,
    submitted_refresh_token: str,
) -> tuple[User, str, str]:
    """
    Validate a refresh token and issue a new token pair (rotation).

    This is the most security-critical function in the auth system.
    The rotation sequence must be:
      1. Decode JWT (validate signature + expiry)
      2. Fetch stored token from Redis
      3. Compare submitted token vs stored token → reject if mismatch
      4. DELETE the old token from Redis IMMEDIATELY (before generating new)
      5. Fetch user from DB
      6. Generate new access + refresh tokens
      7. Store new refresh token in Redis

    Why delete BEFORE generating new tokens (Step 4)?
    This is the replay attack prevention. The window between delete and
    store-new is where an attacker with the old token would fail:
      - Old token: deleted from Redis → comparison fails → 401
      - New token: not yet in Redis → comparison fails → 401
    If we stored the new token FIRST, there's a brief window where both
    old and new tokens are valid simultaneously.

    Why invalidate ALL sessions if a stale token is detected?
    If someone submits a refresh token that doesn't match Redis, it means:
    - The token was already rotated (possible replay attack)
    - OR the user manually cleared their Redis key (legitimate)
    In the replay case, an attacker is attempting to use a stolen token
    that the legitimate user already consumed. Our response: nuclear option —
    delete the current Redis key, forcing EVERYONE (including the attacker
    with a potentially valid newer token) to re-login.

    Args:
        db: Async SQLAlchemy session.
        redis: Async Redis client.
        submitted_refresh_token: The refresh JWT string from the client.

    Returns:
        Tuple of (user, new_access_token, new_refresh_token).

    Raises:
        HTTPException 401: Invalid, expired, or already-rotated token.
    """

    # -------------------------------------------------------------------------
    # Step 1: Decode the JWT (validates signature, expiry, and type claim)
    # decode_token raises HTTPException 401 if anything is wrong.
    # -------------------------------------------------------------------------
    from app.core.security import decode_token  # local import avoids circular deps

    payload = decode_token(submitted_refresh_token, expected_type="refresh")
    user_id_str: str = payload["sub"]

    try:
        user_id = uuid.UUID(user_id_str)
    except ValueError:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Could not validate credentials",
            headers={"WWW-Authenticate": "Bearer"},
        )

    # -------------------------------------------------------------------------
    # Step 2: Fetch the stored refresh token from Redis
    # -------------------------------------------------------------------------
    stored_token = await get_refresh_token(redis, user_id)

    if stored_token is None:
        # Token was deleted (logout) or Redis TTL elapsed.
        # Force re-login — we have no record of this session.
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Session not found or expired. Please log in again.",
            headers={"WWW-Authenticate": "Bearer"},
        )

    # -------------------------------------------------------------------------
    # Step 3: Compare submitted token vs stored token
    # If they don't match, this is either:
    # (a) A replay attack: someone submitting an already-rotated token
    # (b) A bug in the client sending the wrong token
    # Either way, invalidate the entire session as a security measure.
    # -------------------------------------------------------------------------
    if stored_token != submitted_refresh_token:
        # Token mismatch: possible replay attack detected.
        # Immediately invalidate ALL sessions for this user.
        await delete_refresh_token(redis, user_id)
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail=(
                "Invalid refresh token. "
                "If you did not initiate this request, your account may be compromised. "
                "Please log in again."
            ),
            headers={"WWW-Authenticate": "Bearer"},
        )

    # -------------------------------------------------------------------------
    # Step 4: Delete the old refresh token IMMEDIATELY
    # From this point, the old token is invalid. There is a brief window
    # where neither old nor new token is valid — acceptable UX trade-off
    # for correct security behaviour.
    # -------------------------------------------------------------------------
    await delete_refresh_token(redis, user_id)

    # -------------------------------------------------------------------------
    # Step 5: Fetch and validate the user from DB
    # We check DB to catch cases where the account was disabled between
    # login and this refresh attempt.
    # -------------------------------------------------------------------------
    user = await db.get(User, user_id)

    if user is None:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="User no longer exists",
            headers={"WWW-Authenticate": "Bearer"},
        )

    if not user.is_active:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="This account has been disabled. Contact support.",
        )

    # -------------------------------------------------------------------------
    # Step 6 + 7: Generate new token pair and store the new refresh token
    # -------------------------------------------------------------------------
    new_access_token = create_access_token(user.id)
    new_refresh_token = create_refresh_token(user.id)
    await store_refresh_token(redis, user.id, new_refresh_token)

    return user, new_access_token, new_refresh_token


# =============================================================================
# logout
# =============================================================================

async def logout(
    redis: Redis,
    user_id: uuid.UUID,
) -> None:
    """
    Invalidate a user's session by deleting their refresh token from Redis.

    Why is logout simple here?
    The access token is stateless — we cannot revoke it before its 15-minute
    expiry without a blocklist (Phase 3). For most use cases, deleting the
    refresh token is sufficient:
    - No new access tokens can be obtained after logout.
    - The last access token becomes useless in max 15 minutes.

    For high-security scenarios (e.g., "panic logout" after compromise),
    Phase 3 adds an access token blocklist using Redis Sets.

    Why no DB write on logout?
    Redis deletion is O(1) and in-memory — sub-millisecond. A DB write
    would be unnecessary overhead and would create a scalability bottleneck
    for high-frequency login/logout flows.

    Args:
        redis: Async Redis client.
        user_id: The UUID of the user logging out.
    """
    await delete_refresh_token(redis, user_id)
